Add support for istio-1.0.0-snapshot.2

diff --git a/roles/openshift_istio/files/grafana.yaml b/roles/openshift_istio/files/grafana.yaml
--- a/roles/openshift_istio/files/grafana.yaml
+++ b/roles/openshift_istio/files/grafana.yaml
@@ -6,6 +6,65 @@ metadata:
   labels:
     app: grafana
 ---
+# Source: istio/charts/grafana/templates/configmap.yaml
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: istio-grafana-custom-resources
+  namespace: istio-system
+  labels:
+    app: istio-grafana
+    chart: grafana-0.1.0
+    release: redhat-1.0.0-snapshot.2
+    heritage: Tiller
+    istio: grafana
+data:
+  custom-resources.yaml: |-    
+    apiVersion: authentication.istio.io/v1alpha1
+    kind: Policy
+    metadata:
+      name: grafana-ports-mtls-disabled
+      namespace: istio-system
+    spec:
+      targets:
+      - name: grafana
+        ports:
+        - number: 3000
+  run.sh: |-    
+    #!/bin/sh
+    
+    set -x
+    
+    if [ "$#" -ne "1" ]; then
+        echo "first argument should be path to custom resource yaml"
+        exit 1
+    fi
+    
+    pathToResourceYAML=${1}
+    
+    /kubectl get validatingwebhookconfiguration istio-galley 2>/dev/null
+    if [ "$?" -eq 0 ]; then
+        echo "istio-galley validatingwebhookconfiguration found - waiting for istio-galley deployment to be ready"
+        while true; do
+            /kubectl -n istio-system get deployment istio-galley 2>/dev/null
+            if [ "$?" -eq 0 ]; then
+                break
+            fi
+            sleep 1
+        done
+        /kubectl -n istio-system rollout status deployment istio-galley
+        if [ "$?" -ne 0 ]; then
+            echo "istio-galley deployment rollout status check failed"
+            exit 1
+        fi
+        echo "istio-galley deployment ready for configuration validation"
+    fi
+    sleep 5
+    /kubectl apply -f ${pathToResourceYAML}
+    
+
+---
+# Source: istio/charts/grafana/templates/create-custom-resources-job.yaml
 # Source: istio/charts/grafana/templates/service.yaml
 apiVersion: v1
 kind: Service
@@ -16,7 +75,7 @@ metadata:
   labels:
     app: grafana
     chart: grafana-0.1.0
-    release: redhat-1.0.0-snapshot.0
+    release: redhat-1.0.0-snapshot.2
     heritage: Tiller
 spec:
   type: ClusterIP
@@ -27,18 +86,6 @@ spec:
       name: http
   selector:
     app: grafana
----
-apiVersion: authentication.istio.io/v1alpha1
-kind: Policy
-metadata:
-  name: grafana-ports-mtls-disabled
-  namespace: istio-system
-spec:
-  targets:
-  - name: grafana
-    ports:
-    - number: 3000
----
 
 ---
 # Source: istio/charts/grafana/templates/deployment.yaml
@@ -50,7 +97,7 @@ metadata:
   labels:
     app: grafana
     chart: grafana-0.1.0
-    release: redhat-1.0.0-snapshot.0
+    release: redhat-1.0.0-snapshot.2
     heritage: Tiller
 spec:
   replicas: 1
@@ -64,7 +111,7 @@ spec:
       serviceAccountName: grafana
       containers:
         - name: grafana
-          image: "docker.io/istio/grafana:1.0.0-snapshot.0"
+          image: "docker.io/istio/grafana:1.0.0-snapshot.2"
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 3000
@@ -84,7 +131,8 @@ spec:
           - name: GF_PATHS_DATA
             value: /data/grafana
           resources:
-            {}
+            requests:
+              cpu: 10m
             
           volumeMounts:
           - name: data
@@ -125,6 +173,11 @@ spec:
       volumes:
       - name: data
         emptyDir: {}
+
+---
+# Source: istio/charts/grafana/templates/grafana-ports-mtls.yaml
+
+
 ---
 # Source: istio/charts/grafana/templates/ingress.yaml
 
